name: firebase_demo_app
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  auto_route: ^4.2.0
  equatable: 2.0.3
  firebase_auth: 3.3.20
  firebase_core: ^1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  get_it: 7.2.0
  injectable: 1.5.3
  json_annotation: ^4.5.0
  rxdart: 0.27.4

dev_dependencies:
  build_runner: 2.1.11
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1
  build_resolvers: 2.0.9
  injectable_generator: 1.5.3
  auto_route_generator: 4.2.0
  json_serializable: 6.2.0

flutter:
  uses-material-design: true
